name: gql_code_gen
description: GraphQL code generator and file builder for Dart taking *.graphql files as an input.
version: 0.1.2
homepage: https://github.com/gql-dart/gql/tree/master/gql_code_gen
author: Klāvs Priedītis <klavs@prieditis.lv>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  gql: ^0.11.0
  source_span: ^1.5.5
  code_builder: ^3.2.0
  meta: ^1.1.7
  collection: ^1.14.11
  build: ^1.0.0
  dart_style: ^1.2.9
  pedantic: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.7
  gql_pedantic: ^1.0.0
  cats:
    path: ../cats
