name: gql_http_link
version: 0.3.2
description: GQL Terminating Link to execute requests via HTTP using JSON.
repository: https://github.com/gql-dart/gql
environment:
  sdk: ">=2.7.2 <3.0.0"
dependencies:
  collection: ^1.14.13
  gql: ^0.12.1
  gql_exec: ^0.2.4
  gql_link: ^0.3.1
  http: ^0.12.1
  http_parser: ^3.1.4
  meta: ^1.1.7
dev_dependencies:
  gql_pedantic: ^1.0.1
  http_parser: ^3.1.4
  mockito: ^4.1.1
  test: ^1.0.0
