package/gql:
  - gql/*
  - gql/**/*

package/gql_code_builder:
  - gql_code_builder/*
  - gql_code_builder/**/*

package/gql_build:
  - gql_build/*
  - gql_build/**/*

package/gql_dedupe_link:
  - gql_dedupe_link/*
  - gql_dedupe_link/**/*

package/gql_example_cli:
  - gql_example_cli/*
  - gql_example_cli/**/*

package/gql_example_flutter:
  - gql_example_flutter/*
  - gql_example_flutter/**/*

package/gql_http_link:
  - gql_http_link/*
  - gql_http_link/**/*

package/gql_link:
  - gql_link/*
  - gql_link/**/*

package/gql_exec:
  - gql_exec/*
  - gql_exec/**/*

package/gql_pedantic:
  - gql_pedantic/*
  - gql_pedantic/**/*

package/gql_transform_link:
  - gql_transform_link/*
  - gql_transform_link/**/*

package/multipack:
  - multipack/*
  - multipack/**/*
