name: ast_builder

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  args:
  http: ^0.12.0+2
  gql: ^0.11.0
  gql_link: ^0.10.0
  gql_http_link: ^0.2.1

dev_dependencies:
  build_runner: ^1.0.0
  gql_pedantic: ^1.0.0
  gql_code_gen: ^0.1.0

dependency_overrides:
  gql:
    path: ../../../gql
  gql_link:
    path: ../../../gql_link
  gql_http_link:
    path: ../../../gql_http_link
  gql_code_gen:
    path: ../../../gql_code_gen
