name: gql_pedantic
description: Even more opinionated lint rules.
# version: 0.0.0
homepage: https://github.com/gql-dart/gql/tree/master/gql-pedantic
author: Klāvs Priedītis <klavs@prieditis.lv>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
