name: gql
description: GraphQL tools for parsing, transforming and printing GraphQL documents.
version: 0.7.0
homepage: https://github.com/gql-dart/gql/tree/master/gql
author: Klāvs Priedītis <klavs@prieditis.lv>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  source_span: ^1.5.5
  code_builder: ^3.2.0
  meta: ^1.1.7
  collection: ^1.14.12
  build: ^1.0.0
  dart_style: ^1.2.10
  pedantic: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.7
  cats:
    path: ../cats
