name: gql
description: GraphQL tools for parsing, transforming and printing GraphQL documents.
version: 0.0.4
homepage: https://github.com/gql-dart/gql/tree/master/gql
author: Klāvs Priedītis <klavs@prieditis.lv>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  source_span: ^1.5.5
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  cats:
    path: ../cats
