name: gql
version: 0.12.3
homepage: https://github.com/gql-dart/gql/tree/master/gql
description: GraphQL tools for parsing, transforming and printing GraphQL documents.
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  source_span: ^1.5.5
  meta: ^1.1.7
  collection: ^1.14.11
dev_dependencies: 
  test: ^1.0.0
  gql_pedantic: ^1.0.1
  cats: 
    path: ../cats
dependency_overrides: 
  gql_pedantic: 
    path: ../gql_pedantic
  multipack: 
    path: ../multipack
  cats: 
    path: ../cats
  gql_exec: 
    path: ../gql_exec
  gql_link: 
    path: ../gql_link
  gql_transform_link: 
    path: ../gql_transform_link
  gql_http_link: 
    path: ../gql_http_link
  gql_code_builder: 
    path: ../gql_code_builder
  gql_build: 
    path: ../gql_build
  gql_example_cli_github: 
    path: ../gql_example_cli_github
  gql_example_cli: 
    path: ../gql_example_cli
  gql_example_build: 
    path: ../gql_example_build
  gql_dedupe_link: 
    path: ../gql_dedupe_link
