name: gql_code_builder
version: 0.0.10
homepage: https://github.com/gql-dart/gql/tree/master/gql_code_builder
description: Dart code builders taking *.graphql documents and SDL to build useful classes.
environment:
  sdk: ">=2.7.2 <3.0.0"
dependencies:
  gql: ^0.12.1
  code_builder: ^3.2.0
  meta: ^1.1.7
  built_collection: ^4.0.0
  built_value: ^7.0.9
  path: ^1.6.4
  recase: ^3.0.0
dev_dependencies:
  gql_pedantic: ^1.0.1
  build_runner: ^1.7.4
dependency_overrides:
  gql_pedantic:
    path: ../gql_pedantic
  multipack:
    path: ../multipack
  cats:
    path: ../cats
  gql:
    path: ../gql
  gql_exec:
    path: ../gql_exec
  gql_link:
    path: ../gql_link
  gql_transform_link:
    path: ../gql_transform_link
  gql_http_link:
    path: ../gql_http_link
  gql_build:
    path: ../gql_build
  gql_example_cli_github:
    path: ../gql_example_cli_github
  gql_example_cli:
    path: ../gql_example_cli
  gql_example_build:
    path: ../gql_example_build
  gql_dedupe_link:
    path: ../gql_dedupe_link
  code_builder:
    path: ../../code_builder
