name: cats
description: A starting point for Dart libraries or applications.
# version: 1.0.0
homepage: https://github.com/gql-dart/gql/cats
author: Klāvs Priedītis <klavs@prieditis.lv>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  test: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  yaml: ^2.1.16
