name: cats
homepage: https://github.com/gql-dart/gql/cats
description: A starting point for Dart libraries or applications.
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  test: ^1.6.0
dev_dependencies: 
  pedantic: ^1.7.0
  yaml: ^2.1.16
dependency_overrides: 
  gql_pedantic: 
    path: ../gql_pedantic
  multipack: 
    path: ../multipack
  gql: 
    path: ../gql
  gql_exec: 
    path: ../gql_exec
  gql_link: 
    path: ../gql_link
  gql_transform_link: 
    path: ../gql_transform_link
  gql_http_link: 
    path: ../gql_http_link
  gql_code_builder: 
    path: ../gql_code_builder
  gql_build: 
    path: ../gql_build
  gql_example_cli_github: 
    path: ../gql_example_cli_github
  gql_example_cli: 
    path: ../gql_example_cli
  gql_example_build: 
    path: ../gql_example_build
  gql_dedupe_link: 
    path: ../gql_dedupe_link
