name: gql_example_build
environment: 
  sdk: '>=2.7.2 <3.0.0'
dev_dependencies: 
  build_runner: ^1.0.0
  gql_pedantic: ^1.0.2
  gql_build: ^0.0.11
  test: ^1.0.0
dependency_overrides: 
  gql_pedantic: 
    path: ../gql_pedantic
  multipack: 
    path: ../multipack
  cats: 
    path: ../cats
  gql: 
    path: ../gql
  gql_exec: 
    path: ../gql_exec
  gql_link: 
    path: ../gql_link
  gql_transform_link: 
    path: ../gql_transform_link
  gql_http_link: 
    path: ../gql_http_link
  gql_code_builder: 
    path: ../gql_code_builder
  gql_build: 
    path: ../gql_build
  gql_example_cli_github: 
    path: ../gql_example_cli_github
  gql_example_cli: 
    path: ../gql_example_cli
  gql_dedupe_link: 
    path: ../gql_dedupe_link
