name: gql_error_link
version: 0.1.0
homepage: https://github.com/gql-dart/gql/tree/master/gql_error_link
description: GQL Link to handle execution errors and exceptions
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  meta: ^1.1.7
  gql_exec: ^0.2.2
  gql_link: ^0.3.0
dev_dependencies: 
  test: ^1.0.0
  mockito: ^4.1.1
  gql: ^0.12.1
  gql_pedantic: ^1.0.1
