name: gql_dedupe_link
author: Klāvs Priedītis <klavs@prieditis.lv>
version: 1.0.8
homepage: https://github.com/gql-dart/gql/tree/master/gql_dedupe_link
description: GQL Link to deduplicate identical in-flight execution requests
environment: 
  sdk: '>=2.2.2 <3.0.0'
dependencies: 
  meta: ^1.1.7
  gql_exec: ^0.2.0
  gql_link: ^0.2.1
  async: ^2.3.0
dev_dependencies: 
  test: ^1.0.0
  mockito: ^4.1.1
  gql: ^0.12.0
  gql_pedantic: ^1.0.0
