name: gql_dedupe_link
description: GQL Link to deduplicate identical requests
version: 1.0.0
homepage: https://github.com/gql-dart/gql/tree/master/gql_dedupe_link
author: Klāvs Priedītis <klavs@prieditis.lv>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.7
  gql: ^0.7.1
  async: ^2.3.0

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.1.1
  gql_pedantic: ^1.0.0
