name: gql_exec
version: 0.2.4
homepage: https://github.com/gql-dart/gql/tree/master/gql_exec
description: Basis for GraphQL execution layer to support Link and Client.
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  gql: ^0.12.1
  meta: ^1.1.7
  collection: ^1.14.11
dev_dependencies: 
  test: ^1.0.0
  gql_pedantic: ^1.0.1
dependency_overrides: 
  gql_pedantic: 
    path: ../gql_pedantic
  multipack: 
    path: ../multipack
  cats: 
    path: ../cats
  gql: 
    path: ../gql
  gql_link: 
    path: ../gql_link
  gql_transform_link: 
    path: ../gql_transform_link
  gql_http_link: 
    path: ../gql_http_link
  gql_code_builder: 
    path: ../gql_code_builder
  gql_build: 
    path: ../gql_build
  gql_example_cli_github: 
    path: ../gql_example_cli_github
  gql_example_cli: 
    path: ../gql_example_cli
  gql_example_build: 
    path: ../gql_example_build
  gql_dedupe_link: 
    path: ../gql_dedupe_link
