name: gql_ws_link
version: 0.0.1
homepage: https://github.com/gql-dart/gql/tree/master/gql_ws_link
description: GQL websocket link.
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  meta: ^1.1.7
  gql_exec: ^0.2.2
  gql_link: ^0.2.3
  http: ^0.12.0+2
  web_socket_channel: ^1.1.0
  rxdart: ^0.24.0
  uuid: ^2.0.4
dev_dependencies:
  test: ^1.0.0
  mockito: ^4.1.1
  gql: ^0.12.1
  gql_pedantic: ^1.0.1
