name: gql_transform_link
version: 0.1.5
homepage: https://github.com/gql-dart/gql/tree/master/gql_transform_link
description: GQL Link to transform Requests and Responses. May be used to update context, document, variables, data, errors, etc.
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  gql_exec: ^0.2.2
  gql_link: ^0.3.0
dev_dependencies: 
  test: ^1.0.0
  mockito: ^4.1.1
  gql: ^0.12.1
  gql_pedantic: ^1.0.1
dependency_overrides: 
  gql_pedantic: 
    path: ../gql_pedantic
  multipack: 
    path: ../multipack
  cats: 
    path: ../cats
  gql: 
    path: ../gql
  gql_exec: 
    path: ../gql_exec
  gql_link: 
    path: ../gql_link
  gql_http_link: 
    path: ../gql_http_link
  gql_code_builder: 
    path: ../gql_code_builder
  gql_build: 
    path: ../gql_build
  gql_example_cli_github: 
    path: ../gql_example_cli_github
  gql_example_cli: 
    path: ../gql_example_cli
  gql_example_build: 
    path: ../gql_example_build
  gql_dedupe_link: 
    path: ../gql_dedupe_link
