name: gql_example_flutter
version: 1.0.0+1
environment: 
  sdk: '>=2.1.0 <3.0.0'
dependencies: 
  gql: ^0.12.0
  gql_link: ^0.2.1
  gql_http_link: ^0.2.2
  gql_exec: ^0.2.0
  cupertino_icons: ^0.1.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^1.0.0
  gql_pedantic: ^1.0.0
  gql_build: ^0.0.3
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
