name: gql_example_flutter
version: 1.0.0+1
environment:
  sdk: ">=2.7.2 <3.0.0"
dependencies:
  gql: ^0.12.3
  gql_link: ^0.3.0
  gql_http_link: ^0.2.9
  gql_exec: ^0.2.4
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^1.0.0
  gql_pedantic: ^1.0.2
  gql_build: ^0.0.11
  flutter_test:
    sdk: flutter
dependency_overrides:
  gql_pedantic:
    path: ../gql_pedantic
  multipack:
    path: ../multipack
  cats:
    path: ../cats
  gql:
    path: ../gql
  gql_exec:
    path: ../gql_exec
  gql_link:
    path: ../gql_link
  gql_transform_link:
    path: ../gql_transform_link
  gql_http_link:
    path: ../gql_http_link
  gql_code_builder:
    path: ../gql_code_builder
  gql_build:
    path: ../gql_build
  gql_example_cli_github:
    path: ../gql_example_cli_github
  gql_example_cli:
    path: ../gql_example_cli
  gql_example_build:
    path: ../gql_example_build
  gql_dedupe_link:
    path: ../gql_dedupe_link
  code_builder:
    path: ../../code_builder
flutter:
  uses-material-design: true
