name: multipack
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  ansicolor: ^1.0.2
  args: 1.6.0
  directed_graph: ^0.1.2
  pubspec: ^0.1.2
  path: ^1.6.4
dev_dependencies: 
  gql_pedantic: ^1.0.1
dependency_overrides: 
  gql_pedantic: 
    path: ../gql_pedantic
  cats: 
    path: ../cats
  gql: 
    path: ../gql
  gql_exec: 
    path: ../gql_exec
  gql_link: 
    path: ../gql_link
  gql_transform_link: 
    path: ../gql_transform_link
  gql_http_link: 
    path: ../gql_http_link
  gql_code_builder: 
    path: ../gql_code_builder
  gql_build: 
    path: ../gql_build
  gql_example_cli_github: 
    path: ../gql_example_cli_github
  gql_example_cli: 
    path: ../gql_example_cli
  gql_example_build: 
    path: ../gql_example_build
  gql_dedupe_link: 
    path: ../gql_dedupe_link
executables: 
  multipack: null
