name: gql_example_cli
environment: 
  sdk: '>=2.2.0 <3.0.0'
dependencies: 
  args: any
  gql: ^0.12.0
  gql_link: ^0.2.1
  gql_exec: ^0.2.0
  gql_http_link: ^0.2.2
dev_dependencies: 
  build_runner: ^1.0.0
  gql_pedantic: ^1.0.0
  gql_code_gen: ^0.1.0
